version: '3'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - ../volume/my_apps:/usr/src/my_apps
    ports:
      - "8888:8888"  # Jupyter Notebook için port yönlendirme
    command: ["sh", "-c", "chmod -R 777 /workspace && tail -f /dev/null"]
